### ISSUE TITLE
Kwalify mapping default value key '=' not handled properly

### ISSUE THREAD

**Issue by s-ga** [s-ga/kwalify_to_json_schema#8]
As per Kwalify [user guide](http://www.kuwata-lab.com/kwalify/ruby/users-guide.02.html) the `=` key in a mapping stands for the default value.

For example, the following YAML document uses default value of mapping.
```yaml
A: 10
B: 20
=: -1      # default value
```

The converter is dealing witht it as it was a regular key which is incorrect.
